; Generated by SchismC - MASM Assembly Output
; Target: Windows x64

.code

; External functions
extrn ExitProcess:PROC
extrn GetStdHandle:PROC
extrn WriteConsoleA:PROC


get_hello_value PROC
    ; Function prologue
        push rbp        ; Save caller's frame pointer
        mov rbp, rsp    ; Set up new frame pointer
        sub rsp, 32h    ; Allocate local space
    
    ; Function body
        mov rax, 42    ; Return value
    
    ; Function epilogue
        mov rsp, rbp    ; Restore stack pointer
        pop rbp         ; Restore caller's frame pointer
        ret             ; Return to caller
get_hello_value ENDP

get_world_value PROC
    ; Function prologue
        push rbp        ; Save caller's frame pointer
        mov rbp, rsp    ; Set up new frame pointer
        sub rsp, 32h    ; Allocate local space
    
    ; Function body
        mov rax, 24    ; Return value
    
    ; Function epilogue
        mov rsp, rbp    ; Restore stack pointer
        pop rbp         ; Restore caller's frame pointer
        ret             ; Return to caller
get_world_value ENDP

calculate_result PROC
    ; Function prologue
        push rbp        ; Save caller's frame pointer
        mov rbp, rsp    ; Set up new frame pointer
        sub rsp, 32h    ; Allocate local space
    
    ; Function body
        mov rax, 66    ; Return value
    
    ; Function epilogue
        mov rsp, rbp    ; Restore stack pointer
        pop rbp         ; Restore caller's frame pointer
        ret             ; Return to caller
calculate_result ENDP
END
