; Generated by SchismC - MASM Assembly Output
; Target: Windows x64

.code

; External functions
extrn ExitProcess:PROC
extrn GetStdHandle:PROC
extrn WriteConsoleA:PROC

; Windows entry point
main PROC
        sub rsp, 28h        ; Allocate shadow space + align
        call user_main      ; Call user code
        mov rcx, rax        ; Exit code in rcx
        call ExitProcess    ; Exit with return code
        add rsp, 28h        ; Restore stack
        ret
main ENDP

; User main function
user_main PROC
        mov rax, 0          ; Return 0
        ret
user_main ENDP

END
