// Generated by HolyC Windows Port
// Source: examples\hello_world.hc

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdarg.h>
#include <stdbool.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdarg.h>
#include <stdbool.h>

void Print(const char* str) {
    printf("%s", str);
}

int main() {
    Print("Hello, World!");
    return 0;
}
